 var msg = "This example illustrate the use of \"double quote\" within a doublequote sentence";
 

 var n = "My name is Jack \nI live in Russia";
 

 var t = "Hello\tpeople";
 console.log(t + " \n " + msg + n);

 var b = "Remove single character\b";
 console.log(b);

 var h = "I \u2764 you";
 console.log(h); 

 var watch_objects = {
    type_of_watch: "Analogue",
    make: "Philpe Patek",
    price: 20000,
    color: "white Gold",
    isWorking: true
 }
 console.log("I have a " + watch_objects.make + "at the cost of " + watch_objects.price + " that have " + watch_objects.color + " that is working " + watch_objects.true )